name: Artifact Challenge
on: [push]
env:
  Filename: "artifact.txt"
jobs:
  build:
    name: Artifact Challenge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create artifact
        run: echo "Hello, World!" > ${{ env.Filename }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.Filename }}
          path: ${{ env.Filename }}
