name: Complex workflow
#description: This workflow is a complex workflow that uses a number of different features of the workflow engine.
on:
    push:

jobs:
        job1:
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout
                            uses: actions/checkout@v3
                        - name: Get current date
                            id: date
                            run: echo "$(date +'%Y-%m-%d')" >> $GITHUB_STATE
        job2:
                runs-on: windows-latest
                steps:
                        - name: Checkout
                            uses: actions/checkout@v3
                        - name: Get current date
                            id: date
                            run: echo "$(date +'%Y-%m-%d')" >> $GITHUB_STATE
        job3:
                runs-on: macos-latest
                steps:
                        - name: Checkout
                            uses: actions/checkout@v3
                        - name: Get current date
                            id: date
                            run: echo "$(date +'%Y-%m-%d')" >> $GITHUB_STATE
        job4:
                needs: [job1, job2, job3]
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout
                            uses: actions/checkout@v3
                        - name: Get current date
                            id: date
                            run: echo "$(date +'%Y-%m-%d')" >> $GITHUB_STATE
